import Head from "next/head";
import Layout from "../components/Layout";
import FrontPage from "./Home";
import { AuthProvider } from "../context/AuthContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>
        <Layout>
          <FrontPage />
        </Layout>
      </AuthProvider>
    </>
  );
}
