import Head from "next/head";
import Layout from "../components/Layout";
import FrontPage from "./Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <FrontPage />
      </Layout>
    </>
  );
}
